version: '3.6'

services:
  bddmysql:
    container_name: "bdbJee"
    build:
      context: ./bdd
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa